### ISSUE TITLE
Sign In with Twitter Broken

### ISSUE THREAD

**Issue by kgenoe** [itsjavi/supereffective.gg#17]
**Issue**
Currently it is not possible to access accounts (at least my account) that are signed in through Twitter. This may be releated to Twitter recently cutting off some 3rd party applications ([link](https://www.macstories.net/stories/twitter-intentionally-ends-third-party-app-developer-access-to-its-apis/)), but that's just speculation. 

**Reproducability**
I've been able to reproduce this issue in Safari on iOS, Safari on macOS, Chrome on macOS. All of these platforms I've tested with my normal environment, and a fully clean environment.

**Demo**

https://user-images.githubusercontent.com/9827910/212984998-48a31f90-3631-49d8-a92a-34ec09e72d78.mov

**Comment by Tyrdok** [comment]
Receiving this same issue with github sign in on chrome on mobile.

**Comment by itsjavi** [comment]
I fixed this, finally, sorry for the delay.

Login issues will now show a more useful error message:

![image](https://user-images.githubusercontent.com/122741/230763110-40523467-b49c-4904-afcf-a74f35ccc4bd.png)

**Comment by Tyrdok** [comment]
Thanks mate,
I was very confused as I wasn't trying to connect it to my gmail account.
