### ISSUE TITLE
Saved pokedex not loading

### ISSUE THREAD

**Issue by Whopperboxers** [itsjavi/supereffective.gg#18]
I started a pokedex and got about 80 pokemon selected. When I went to reopen it, it would not load. I even left it overnight just in case it was taking a while on the server, but nope. I don't want to have to refill in my pokemon each time I log in; that's most the reason I chose to try this app. Please help with the solution. Thank you!

**Comment by itsjavi** [comment]
what's the link of your dex?
without that I cannot help

**Comment by Whopperboxers** [comment]
https://supereffective.gg/apps/livingdex/dQllXWUDQFouodn8ioUh

Thank you

**Comment by itsjavi** [comment]
I can see it, maybe is your browser or your internet connection.

What browser are you using? (browser name, version and operative system)

![image](https://user-images.githubusercontent.com/122741/218324112-b1c5d071-da99-4fb4-a808-1a437d657d19.png)

**Comment by Whopperboxers** [comment]
Chrome, Version 96.0.4664.110, Windows 11

**Comment by Whopperboxers** [comment]
I can see that the file is there on the screen that shows your different
dexes, it just doesn't load for me.

**Comment by itsjavi** [comment]
It's also working for me with Windows 11 and Chrome 96 (you are using a very old version anyway)

It might be your internet connection, or some extension that you have installed.
Please update your browser or use another one like Firefox or Edge.

![image](https://user-images.githubusercontent.com/122741/218325144-5bb3bd74-077b-4ca5-b838-1a817fb1ceff.png)

**Comment by Whopperboxers** [comment]
I got it to work on Edge. I should have tried that first. Thanks for the
help
